version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "julia"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "CUDACore"
      - dependency-name: "CUDATools"
      - dependency-name: "cuBLAS"
      - dependency-name: "cuFFT"
      - dependency-name: "cuRAND"
      - dependency-name: "cuSOLVER"
      - dependency-name: "cuSPARSE"
