coverage:
  ignore:
    # generated wrappers
    - "CUDACore/lib/*/lib*.jl"
    - "lib/*/src/lib*.jl"
    # not package code
    - "test/"
    - "lib/*/test/**"
    - "res/"
    - "docs/"
    - "perf/"
  status:
    patch: false
    project: false
    changes: false
