name = "CUDA"
uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
version = "6.0.0"

[workspace]
projects = ["test", "docs", "perf", "examples",
            "CUDACore",
            "CUDATools",
            "lib/cupti", "lib/nvml",
            "lib/cublas", "lib/cusparse", "lib/cusolver", "lib/cufft", "lib/curand",
            "lib/cudnn", "lib/cutensor", "lib/cutensornet", "lib/custatevec"]

[deps]
CUDACore = "bd0ed864-bdfe-4181-a5ed-ce625a5fdea2"
CUDATools = "9ec180c6-1c07-47c7-9e6e-ebefa4d1f6d0"
Republic = "27243419-9dde-4721-b67c-fd63626fea7f"
cuBLAS = "182d3088-87b7-4494-8cad-fc6afaa545bc"
cuFFT = "533571aa-0936-420e-b4be-9c66f5f626ca"
cuRAND = "20fd9a0b-12d5-4c2f-a8af-7c34e9e60431"
cuSOLVER = "887afef0-6a32-4de5-add4-7827692ba8fc"
cuSPARSE = "b26da814-b3bc-49ef-b0ee-c816305aa060"

[sources]
CUDACore = {path = "CUDACore"}
CUDATools = {path = "CUDATools"}
cuBLAS = {path = "lib/cublas"}
cuFFT = {path = "lib/cufft"}
cuRAND = {path = "lib/curand"}
cuSOLVER = {path = "lib/cusolver"}
cuSPARSE = {path = "lib/cusparse"}

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"

[compat]
CUDACore = "=6.0.0"
CUDATools = "=6.0.0"
Republic = "2.1"
cuBLAS = "=6.0.0"
cuFFT = "=6.0.0"
cuRAND = "=6.0.0"
cuSOLVER = "=6.0.0"
cuSPARSE = "=6.0.0"
julia = "1.10"
