name = "CUDA"
uuid = "052768ef-5323-5732-b1bb-66c8b64840ba"
version = "6.0.0"

[workspace]
projects = ["test", "docs", "perf", "examples",
            "CUDACore",
            "lib/cublas", "lib/cusparse", "lib/cusolver", "lib/cufft", "lib/curand",
            "lib/cudnn", "lib/cutensor", "lib/cutensornet", "lib/custatevec"]

[deps]
CUDACore = "bd0ed864-bdfe-4181-a5ed-ce625a5fdea2"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
cuBLAS = "182d3088-87b7-4494-8cad-fc6afaa545bc"
cuFFT = "533571aa-0936-420e-b4be-9c66f5f626ca"
cuRAND = "20fd9a0b-12d5-4c2f-a8af-7c34e9e60431"
cuSOLVER = "887afef0-6a32-4de5-add4-7827692ba8fc"
cuSPARSE = "b26da814-b3bc-49ef-b0ee-c816305aa060"

[sources]
CUDACore = {path = "CUDACore"}
cuBLAS = {path = "lib/cublas"}
cuFFT = {path = "lib/cufft"}
cuRAND = {path = "lib/curand"}
cuSOLVER = {path = "lib/cusolver"}
cuSPARSE = {path = "lib/cusparse"}

[compat]
CUDACore = "=6.0.0"
Reexport = "1.0"
cuBLAS = "=6.0.0"
cuFFT = "=6.0.0"
cuRAND = "=6.0.0"
cuSOLVER = "=6.0.0"
cuSPARSE = "=6.0.0"
julia = "1.10"
