# This file is automatically generated. Do not edit!
# To re-generate, execute res/wrap/wrap.jl

using CEnum: CEnum, @cenum

# CUFFT uses CUDA runtime objects, which are compatible with our driver usage
const cudaStream_t = CUstream

# outlined functionality to avoid GC frame allocation
@noinline function throw_api_error(res)
    if res == CUFFT_ALLOC_FAILED
        throw(OutOfGPUMemoryError())
    else
        throw(CUFFTError(res))
    end
end

@inline function check(f)
    retry_if(res) = res in (CUFFT_ALLOC_FAILED,
                            CUFFT_INTERNAL_ERROR)
    res = retry_reclaim(f, retry_if)

    if res != CUFFT_SUCCESS
        throw_api_error(res)
    end
end

@cenum cudaXtCopyType_t::UInt32 begin
    LIB_XT_COPY_HOST_TO_DEVICE = 0
    LIB_XT_COPY_DEVICE_TO_HOST = 1
    LIB_XT_COPY_DEVICE_TO_DEVICE = 2
end

const cudaLibXtCopyType = cudaXtCopyType_t

@cenum libFormat_t::UInt32 begin
    LIB_FORMAT_CUFFT = 0
    LIB_FORMAT_UNDEFINED = 1
end

const libFormat = libFormat_t

struct cudaXtDesc_t
    version::Cint
    nGPUs::Cint
    GPUs::NTuple{64,Cint}
    data::NTuple{64,Ptr{Cvoid}}
    size::NTuple{64,Csize_t}
    cudaXtState::Ptr{Cvoid}
end

const cudaXtDesc = cudaXtDesc_t

struct cudaLibXtDesc_t
    version::Cint
    descriptor::Ptr{cudaXtDesc}
    library::libFormat
    subFormat::Cint
    libDescriptor::Ptr{Cvoid}
end

const cudaLibXtDesc = cudaLibXtDesc_t

@cenum cufftResult_t::UInt32 begin
    CUFFT_SUCCESS = 0
    CUFFT_INVALID_PLAN = 1
    CUFFT_ALLOC_FAILED = 2
    CUFFT_INVALID_TYPE = 3
    CUFFT_INVALID_VALUE = 4
    CUFFT_INTERNAL_ERROR = 5
    CUFFT_EXEC_FAILED = 6
    CUFFT_SETUP_FAILED = 7
    CUFFT_INVALID_SIZE = 8
    CUFFT_UNALIGNED_DATA = 9
    CUFFT_INVALID_DEVICE = 11
    CUFFT_NO_WORKSPACE = 13
    CUFFT_NOT_IMPLEMENTED = 14
    CUFFT_NOT_SUPPORTED = 16
    CUFFT_MISSING_DEPENDENCY = 17
    CUFFT_NVRTC_FAILURE = 18
    CUFFT_NVJITLINK_FAILURE = 19
    CUFFT_NVSHMEM_FAILURE = 20
end

const cufftResult = cufftResult_t

const cufftReal = Cfloat

const cufftDoubleReal = Cdouble

const cufftComplex = cuComplex

const cufftDoubleComplex = cuDoubleComplex

@cenum cufftType_t::UInt32 begin
    CUFFT_R2C = 42
    CUFFT_C2R = 44
    CUFFT_C2C = 41
    CUFFT_D2Z = 106
    CUFFT_Z2D = 108
    CUFFT_Z2Z = 105
end

const cufftType = cufftType_t

@cenum cufftCompatibility_t::UInt32 begin
    CUFFT_COMPATIBILITY_FFTW_PADDING = 1
end

const cufftCompatibility = cufftCompatibility_t

const cufftHandle = Cint

@checked function cufftPlan1d(plan, nx, type, batch)
    initialize_context()
    @gcsafe_ccall libcufft.cufftPlan1d(plan::Ptr{cufftHandle}, nx::Cint, type::cufftType,
                                       batch::Cint)::cufftResult
end

@checked function cufftPlan2d(plan, nx, ny, type)
    initialize_context()
    @gcsafe_ccall libcufft.cufftPlan2d(plan::Ptr{cufftHandle}, nx::Cint, ny::Cint,
                                       type::cufftType)::cufftResult
end

@checked function cufftPlan3d(plan, nx, ny, nz, type)
    initialize_context()
    @gcsafe_ccall libcufft.cufftPlan3d(plan::Ptr{cufftHandle}, nx::Cint, ny::Cint, nz::Cint,
                                       type::cufftType)::cufftResult
end

@checked function cufftPlanMany(plan, rank, n, inembed, istride, idist, onembed, ostride,
                                odist, type, batch)
    initialize_context()
    @gcsafe_ccall libcufft.cufftPlanMany(plan::Ptr{cufftHandle}, rank::Cint, n::Ptr{Cint},
                                         inembed::Ptr{Cint}, istride::Cint, idist::Cint,
                                         onembed::Ptr{Cint}, ostride::Cint, odist::Cint,
                                         type::cufftType, batch::Cint)::cufftResult
end

@checked function cufftMakePlan1d(plan, nx, type, batch, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftMakePlan1d(plan::cufftHandle, nx::Cint, type::cufftType,
                                           batch::Cint, workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftMakePlan2d(plan, nx, ny, type, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftMakePlan2d(plan::cufftHandle, nx::Cint, ny::Cint,
                                           type::cufftType,
                                           workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftMakePlan3d(plan, nx, ny, nz, type, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftMakePlan3d(plan::cufftHandle, nx::Cint, ny::Cint, nz::Cint,
                                           type::cufftType,
                                           workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftMakePlanMany(plan, rank, n, inembed, istride, idist, onembed,
                                    ostride, odist, type, batch, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftMakePlanMany(plan::cufftHandle, rank::Cint, n::Ptr{Cint},
                                             inembed::Ptr{Cint}, istride::Cint, idist::Cint,
                                             onembed::Ptr{Cint}, ostride::Cint, odist::Cint,
                                             type::cufftType, batch::Cint,
                                             workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftMakePlanMany64(plan, rank, n, inembed, istride, idist, onembed,
                                      ostride, odist, type, batch, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftMakePlanMany64(plan::cufftHandle, rank::Cint,
                                               n::Ptr{Clonglong}, inembed::Ptr{Clonglong},
                                               istride::Clonglong, idist::Clonglong,
                                               onembed::Ptr{Clonglong}, ostride::Clonglong,
                                               odist::Clonglong, type::cufftType,
                                               batch::Clonglong,
                                               workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftGetSizeMany64(plan, rank, n, inembed, istride, idist, onembed,
                                     ostride, odist, type, batch, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftGetSizeMany64(plan::cufftHandle, rank::Cint,
                                              n::Ptr{Clonglong}, inembed::Ptr{Clonglong},
                                              istride::Clonglong, idist::Clonglong,
                                              onembed::Ptr{Clonglong}, ostride::Clonglong,
                                              odist::Clonglong, type::cufftType,
                                              batch::Clonglong,
                                              workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftEstimate1d(nx, type, batch, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftEstimate1d(nx::Cint, type::cufftType, batch::Cint,
                                           workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftEstimate2d(nx, ny, type, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftEstimate2d(nx::Cint, ny::Cint, type::cufftType,
                                           workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftEstimate3d(nx, ny, nz, type, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftEstimate3d(nx::Cint, ny::Cint, nz::Cint, type::cufftType,
                                           workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftEstimateMany(rank, n, inembed, istride, idist, onembed, ostride,
                                    odist, type, batch, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftEstimateMany(rank::Cint, n::Ptr{Cint}, inembed::Ptr{Cint},
                                             istride::Cint, idist::Cint, onembed::Ptr{Cint},
                                             ostride::Cint, odist::Cint, type::cufftType,
                                             batch::Cint,
                                             workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftCreate(handle)
    initialize_context()
    @gcsafe_ccall libcufft.cufftCreate(handle::Ptr{cufftHandle})::cufftResult
end

@checked function cufftGetSize1d(handle, nx, type, batch, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftGetSize1d(handle::cufftHandle, nx::Cint, type::cufftType,
                                          batch::Cint, workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftGetSize2d(handle, nx, ny, type, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftGetSize2d(handle::cufftHandle, nx::Cint, ny::Cint,
                                          type::cufftType,
                                          workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftGetSize3d(handle, nx, ny, nz, type, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftGetSize3d(handle::cufftHandle, nx::Cint, ny::Cint, nz::Cint,
                                          type::cufftType,
                                          workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftGetSizeMany(handle, rank, n, inembed, istride, idist, onembed,
                                   ostride, odist, type, batch, workArea)
    initialize_context()
    @gcsafe_ccall libcufft.cufftGetSizeMany(handle::cufftHandle, rank::Cint, n::Ptr{Cint},
                                            inembed::Ptr{Cint}, istride::Cint, idist::Cint,
                                            onembed::Ptr{Cint}, ostride::Cint, odist::Cint,
                                            type::cufftType, batch::Cint,
                                            workArea::Ptr{Csize_t})::cufftResult
end

@checked function cufftGetSize(handle, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftGetSize(handle::cufftHandle,
                                        workSize::Ptr{Csize_t})::cufftResult
end

@checked function cufftSetWorkArea(plan, workArea)
    initialize_context()
    @gcsafe_ccall libcufft.cufftSetWorkArea(plan::cufftHandle,
                                            workArea::CuPtr{Cvoid})::cufftResult
end

@checked function cufftSetAutoAllocation(plan, autoAllocate)
    initialize_context()
    @gcsafe_ccall libcufft.cufftSetAutoAllocation(plan::cufftHandle,
                                                  autoAllocate::Cint)::cufftResult
end

@checked function cufftExecC2C(plan, idata, odata, direction)
    initialize_context()
    @gcsafe_ccall libcufft.cufftExecC2C(plan::cufftHandle, idata::CuPtr{cufftComplex},
                                        odata::CuPtr{cufftComplex},
                                        direction::Cint)::cufftResult
end

@checked function cufftExecR2C(plan, idata, odata)
    initialize_context()
    @gcsafe_ccall libcufft.cufftExecR2C(plan::cufftHandle, idata::CuPtr{cufftReal},
                                        odata::CuPtr{cufftComplex})::cufftResult
end

@checked function cufftExecC2R(plan, idata, odata)
    initialize_context()
    @gcsafe_ccall libcufft.cufftExecC2R(plan::cufftHandle, idata::CuPtr{cufftComplex},
                                        odata::CuPtr{cufftReal})::cufftResult
end

@checked function cufftExecZ2Z(plan, idata, odata, direction)
    initialize_context()
    @gcsafe_ccall libcufft.cufftExecZ2Z(plan::cufftHandle, idata::CuPtr{cufftDoubleComplex},
                                        odata::CuPtr{cufftDoubleComplex},
                                        direction::Cint)::cufftResult
end

@checked function cufftExecD2Z(plan, idata, odata)
    initialize_context()
    @gcsafe_ccall libcufft.cufftExecD2Z(plan::cufftHandle, idata::CuPtr{cufftDoubleReal},
                                        odata::CuPtr{cufftDoubleComplex})::cufftResult
end

@checked function cufftExecZ2D(plan, idata, odata)
    initialize_context()
    @gcsafe_ccall libcufft.cufftExecZ2D(plan::cufftHandle, idata::CuPtr{cufftDoubleComplex},
                                        odata::CuPtr{cufftDoubleReal})::cufftResult
end

@checked function cufftSetStream(plan, stream)
    initialize_context()
    @gcsafe_ccall libcufft.cufftSetStream(plan::cufftHandle,
                                          stream::cudaStream_t)::cufftResult
end

@checked function cufftDestroy(plan)
    initialize_context()
    @gcsafe_ccall libcufft.cufftDestroy(plan::cufftHandle)::cufftResult
end

@checked function cufftGetVersion(version)
    @gcsafe_ccall libcufft.cufftGetVersion(version::Ptr{Cint})::cufftResult
end

@checked function cufftGetProperty(type, value)
    @gcsafe_ccall libcufft.cufftGetProperty(type::libraryPropertyType,
                                            value::Ptr{Cint})::cufftResult
end

@cenum cufftProperty_t::UInt32 begin
    NVFFT_PLAN_PROPERTY_INT64_PATIENT_JIT = 1
    NVFFT_PLAN_PROPERTY_INT64_MAX_NUM_HOST_THREADS = 2
end

const cufftProperty = cufftProperty_t

@checked function cufftSetPlanPropertyInt64(plan, property, inputValueInt)
    initialize_context()
    @gcsafe_ccall libcufft.cufftSetPlanPropertyInt64(plan::cufftHandle,
                                                     property::cufftProperty,
                                                     inputValueInt::Clonglong)::cufftResult
end

@checked function cufftGetPlanPropertyInt64(plan, property, returnPtrValue)
    initialize_context()
    @gcsafe_ccall libcufft.cufftGetPlanPropertyInt64(plan::cufftHandle,
                                                     property::cufftProperty,
                                                     returnPtrValue::Ptr{Clonglong})::cufftResult
end

@checked function cufftResetPlanProperty(plan, property)
    initialize_context()
    @gcsafe_ccall libcufft.cufftResetPlanProperty(plan::cufftHandle,
                                                  property::cufftProperty)::cufftResult
end

@cenum cufftXtSubFormat_t::UInt32 begin
    CUFFT_XT_FORMAT_INPUT = 0
    CUFFT_XT_FORMAT_OUTPUT = 1
    CUFFT_XT_FORMAT_INPLACE = 2
    CUFFT_XT_FORMAT_INPLACE_SHUFFLED = 3
    CUFFT_XT_FORMAT_1D_INPUT_SHUFFLED = 4
    CUFFT_XT_FORMAT_DISTRIBUTED_INPUT = 5
    CUFFT_XT_FORMAT_DISTRIBUTED_OUTPUT = 6
    CUFFT_FORMAT_UNDEFINED = 7
end

const cufftXtSubFormat = cufftXtSubFormat_t

@cenum cufftXtCopyType_t::UInt32 begin
    CUFFT_COPY_HOST_TO_DEVICE = 0
    CUFFT_COPY_DEVICE_TO_HOST = 1
    CUFFT_COPY_DEVICE_TO_DEVICE = 2
    CUFFT_COPY_UNDEFINED = 3
end

const cufftXtCopyType = cufftXtCopyType_t

@cenum cufftXtQueryType_t::UInt32 begin
    CUFFT_QUERY_1D_FACTORS = 0
    CUFFT_QUERY_UNDEFINED = 1
end

const cufftXtQueryType = cufftXtQueryType_t

struct cufftXt1dFactors_t
    size::Clonglong
    stringCount::Clonglong
    stringLength::Clonglong
    substringLength::Clonglong
    factor1::Clonglong
    factor2::Clonglong
    stringMask::Clonglong
    substringMask::Clonglong
    factor1Mask::Clonglong
    factor2Mask::Clonglong
    stringShift::Cint
    substringShift::Cint
    factor1Shift::Cint
    factor2Shift::Cint
end

const cufftXt1dFactors = cufftXt1dFactors_t

@cenum cufftXtWorkAreaPolicy_t::UInt32 begin
    CUFFT_WORKAREA_MINIMAL = 0
    CUFFT_WORKAREA_USER = 1
    CUFFT_WORKAREA_PERFORMANCE = 2
end

const cufftXtWorkAreaPolicy = cufftXtWorkAreaPolicy_t

@checked function cufftXtSetGPUs(handle, nGPUs, whichGPUs)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtSetGPUs(handle::cufftHandle, nGPUs::Cint,
                                          whichGPUs::Ptr{Cint})::cufftResult
end

@checked function cufftXtMalloc(plan, descriptor, format)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtMalloc(plan::cufftHandle,
                                         descriptor::Ptr{Ptr{cudaLibXtDesc}},
                                         format::cufftXtSubFormat)::cufftResult
end

@checked function cufftXtMemcpy(plan, dstPointer, srcPointer, type)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtMemcpy(plan::cufftHandle, dstPointer::CuPtr{Cvoid},
                                         srcPointer::CuPtr{Cvoid},
                                         type::cufftXtCopyType)::cufftResult
end

@checked function cufftXtFree(descriptor)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtFree(descriptor::Ptr{cudaLibXtDesc})::cufftResult
end

@checked function cufftXtSetWorkArea(plan, workArea)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtSetWorkArea(plan::cufftHandle,
                                              workArea::Ptr{Ptr{Cvoid}})::cufftResult
end

@checked function cufftXtExecDescriptorC2C(plan, input, output, direction)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtExecDescriptorC2C(plan::cufftHandle,
                                                    input::Ptr{cudaLibXtDesc},
                                                    output::Ptr{cudaLibXtDesc},
                                                    direction::Cint)::cufftResult
end

@checked function cufftXtExecDescriptorR2C(plan, input, output)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtExecDescriptorR2C(plan::cufftHandle,
                                                    input::Ptr{cudaLibXtDesc},
                                                    output::Ptr{cudaLibXtDesc})::cufftResult
end

@checked function cufftXtExecDescriptorC2R(plan, input, output)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtExecDescriptorC2R(plan::cufftHandle,
                                                    input::Ptr{cudaLibXtDesc},
                                                    output::Ptr{cudaLibXtDesc})::cufftResult
end

@checked function cufftXtExecDescriptorZ2Z(plan, input, output, direction)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtExecDescriptorZ2Z(plan::cufftHandle,
                                                    input::Ptr{cudaLibXtDesc},
                                                    output::Ptr{cudaLibXtDesc},
                                                    direction::Cint)::cufftResult
end

@checked function cufftXtExecDescriptorD2Z(plan, input, output)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtExecDescriptorD2Z(plan::cufftHandle,
                                                    input::Ptr{cudaLibXtDesc},
                                                    output::Ptr{cudaLibXtDesc})::cufftResult
end

@checked function cufftXtExecDescriptorZ2D(plan, input, output)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtExecDescriptorZ2D(plan::cufftHandle,
                                                    input::Ptr{cudaLibXtDesc},
                                                    output::Ptr{cudaLibXtDesc})::cufftResult
end

@checked function cufftXtQueryPlan(plan, queryStruct, queryType)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtQueryPlan(plan::cufftHandle, queryStruct::CuPtr{Cvoid},
                                            queryType::cufftXtQueryType)::cufftResult
end

@cenum cufftXtCallbackType_t::UInt32 begin
    CUFFT_CB_LD_COMPLEX = 0
    CUFFT_CB_LD_COMPLEX_DOUBLE = 1
    CUFFT_CB_LD_REAL = 2
    CUFFT_CB_LD_REAL_DOUBLE = 3
    CUFFT_CB_ST_COMPLEX = 4
    CUFFT_CB_ST_COMPLEX_DOUBLE = 5
    CUFFT_CB_ST_REAL = 6
    CUFFT_CB_ST_REAL_DOUBLE = 7
    CUFFT_CB_UNDEFINED = 8
end

const cufftXtCallbackType = cufftXtCallbackType_t

# typedef cufftComplex ( * cufftCallbackLoadC ) ( void * dataIn , size_t offset , void * callerInfo , void * sharedPointer )
const cufftCallbackLoadC = Ptr{Cvoid}

# typedef cufftDoubleComplex ( * cufftCallbackLoadZ ) ( void * dataIn , size_t offset , void * callerInfo , void * sharedPointer )
const cufftCallbackLoadZ = Ptr{Cvoid}

# typedef cufftReal ( * cufftCallbackLoadR ) ( void * dataIn , size_t offset , void * callerInfo , void * sharedPointer )
const cufftCallbackLoadR = Ptr{Cvoid}

# typedef cufftDoubleReal ( * cufftCallbackLoadD ) ( void * dataIn , size_t offset , void * callerInfo , void * sharedPointer )
const cufftCallbackLoadD = Ptr{Cvoid}

# typedef void ( * cufftCallbackStoreC ) ( void * dataOut , size_t offset , cufftComplex element , void * callerInfo , void * sharedPointer )
const cufftCallbackStoreC = Ptr{Cvoid}

# typedef void ( * cufftCallbackStoreZ ) ( void * dataOut , size_t offset , cufftDoubleComplex element , void * callerInfo , void * sharedPointer )
const cufftCallbackStoreZ = Ptr{Cvoid}

# typedef void ( * cufftCallbackStoreR ) ( void * dataOut , size_t offset , cufftReal element , void * callerInfo , void * sharedPointer )
const cufftCallbackStoreR = Ptr{Cvoid}

# typedef void ( * cufftCallbackStoreD ) ( void * dataOut , size_t offset , cufftDoubleReal element , void * callerInfo , void * sharedPointer )
const cufftCallbackStoreD = Ptr{Cvoid}

# typedef cufftComplex ( * cufftJITCallbackLoadC ) ( void * dataIn , unsigned long long offset , void * callerInfo , void * sharedPointer )
const cufftJITCallbackLoadC = Ptr{Cvoid}

# typedef cufftDoubleComplex ( * cufftJITCallbackLoadZ ) ( void * dataIn , unsigned long long offset , void * callerInfo , void * sharedPointer )
const cufftJITCallbackLoadZ = Ptr{Cvoid}

# typedef cufftReal ( * cufftJITCallbackLoadR ) ( void * dataIn , unsigned long long offset , void * callerInfo , void * sharedPointer )
const cufftJITCallbackLoadR = Ptr{Cvoid}

# typedef cufftDoubleReal ( * cufftJITCallbackLoadD ) ( void * dataIn , unsigned long long offset , void * callerInfo , void * sharedPointer )
const cufftJITCallbackLoadD = Ptr{Cvoid}

# typedef void ( * cufftJITCallbackStoreC ) ( void * dataOut , unsigned long long offset , cufftComplex element , void * callerInfo , void * sharedPointer )
const cufftJITCallbackStoreC = Ptr{Cvoid}

# typedef void ( * cufftJITCallbackStoreZ ) ( void * dataOut , unsigned long long offset , cufftDoubleComplex element , void * callerInfo , void * sharedPointer )
const cufftJITCallbackStoreZ = Ptr{Cvoid}

# typedef void ( * cufftJITCallbackStoreR ) ( void * dataOut , unsigned long long offset , cufftReal element , void * callerInfo , void * sharedPointer )
const cufftJITCallbackStoreR = Ptr{Cvoid}

# typedef void ( * cufftJITCallbackStoreD ) ( void * dataOut , unsigned long long offset , cufftDoubleReal element , void * callerInfo , void * sharedPointer )
const cufftJITCallbackStoreD = Ptr{Cvoid}

@checked function cufftXtSetCallback(plan, callback_routine, cbType, caller_info)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtSetCallback(plan::cufftHandle,
                                              callback_routine::Ptr{Ptr{Cvoid}},
                                              cbType::cufftXtCallbackType,
                                              caller_info::Ptr{Ptr{Cvoid}})::cufftResult
end

@checked function cufftXtClearCallback(plan, cbType)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtClearCallback(plan::cufftHandle,
                                                cbType::cufftXtCallbackType)::cufftResult
end

@checked function cufftXtSetCallbackSharedSize(plan, cbType, sharedSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtSetCallbackSharedSize(plan::cufftHandle,
                                                        cbType::cufftXtCallbackType,
                                                        sharedSize::Csize_t)::cufftResult
end

@checked function cufftXtSetJITCallback(plan, lto_callback_symbol_name, lto_callback_fatbin,
                                        lto_callback_fatbin_size, type, caller_info)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtSetJITCallback(plan::cufftHandle,
                                                 lto_callback_symbol_name::Cstring,
                                                 lto_callback_fatbin::Ptr{Cvoid},
                                                 lto_callback_fatbin_size::Csize_t,
                                                 type::cufftXtCallbackType,
                                                 caller_info::Ptr{Ptr{Cvoid}})::cufftResult
end

@checked function cufftXtMakePlanMany(plan, rank, n, inembed, istride, idist, inputtype,
                                      onembed, ostride, odist, outputtype, batch, workSize,
                                      executiontype)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtMakePlanMany(plan::cufftHandle, rank::Cint,
                                               n::Ptr{Clonglong}, inembed::Ptr{Clonglong},
                                               istride::Clonglong, idist::Clonglong,
                                               inputtype::cudaDataType,
                                               onembed::Ptr{Clonglong}, ostride::Clonglong,
                                               odist::Clonglong, outputtype::cudaDataType,
                                               batch::Clonglong, workSize::Ptr{Csize_t},
                                               executiontype::cudaDataType)::cufftResult
end

@checked function cufftXtGetSizeMany(plan, rank, n, inembed, istride, idist, inputtype,
                                     onembed, ostride, odist, outputtype, batch, workSize,
                                     executiontype)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtGetSizeMany(plan::cufftHandle, rank::Cint,
                                              n::Ptr{Clonglong}, inembed::Ptr{Clonglong},
                                              istride::Clonglong, idist::Clonglong,
                                              inputtype::cudaDataType,
                                              onembed::Ptr{Clonglong}, ostride::Clonglong,
                                              odist::Clonglong, outputtype::cudaDataType,
                                              batch::Clonglong, workSize::Ptr{Csize_t},
                                              executiontype::cudaDataType)::cufftResult
end

@checked function cufftXtExec(plan, input, output, direction)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtExec(plan::cufftHandle, input::CuPtr{Cvoid},
                                       output::CuPtr{Cvoid}, direction::Cint)::cufftResult
end

@checked function cufftXtExecDescriptor(plan, input, output, direction)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtExecDescriptor(plan::cufftHandle,
                                                 input::Ptr{cudaLibXtDesc},
                                                 output::Ptr{cudaLibXtDesc},
                                                 direction::Cint)::cufftResult
end

@checked function cufftXtSetWorkAreaPolicy(plan, policy, workSize)
    initialize_context()
    @gcsafe_ccall libcufft.cufftXtSetWorkAreaPolicy(plan::cufftHandle,
                                                    policy::cufftXtWorkAreaPolicy,
                                                    workSize::Ptr{Csize_t})::cufftResult
end

const CUDA_XT_DESCRIPTOR_VERSION = 0x01000000

const MAX_CUDA_DESCRIPTOR_GPUS = 64

# Skipping MacroDefinition: CUFFTAPI __attribute__ ( ( visibility ( "default" ) ) )

const MAX_CUFFT_ERROR = 0x15

const CUFFT_FORWARD = -1

const CUFFT_INVERSE = 1

const CUFFT_COMPATIBILITY_DEFAULT = CUFFT_COMPATIBILITY_FFTW_PADDING

const MAX_SHIM_RANK = 3

const CUFFT_PLAN_NULL = -1
