# Ensure that functions marked with `@device_function(s)` don't leak GPU-only code into the
# global method table. If a definition escapes the rewrite (e.g. because the expansion of
# `@doc` changed shape, as happened on Julia 1.13), it becomes a CPU-callable method that
# contains GPU-only intrinsics or inline PTX. Ahead-of-time compilation (PackageCompiler,
# juliac's compile-all pass) then fails with errors like
# `LLVM ERROR: Cannot select: intrinsic %llvm.nvvm.barrier0` (JuliaGPU/GPUCompiler.jl#611).

@testset "device functions are CPU stubs" begin
    root = joinpath(pkgdir(CUDACore), "src", "device")

    # syntactically collect the (name, line) of function definitions within
    # `@device_function(s)` blocks. The line is the one of the definition's body block,
    # which is what Julia records as the method's location.
    function definition(ex)
        Meta.isexpr(ex, (:function, :(=)), 2) || return nothing
        sig, body = ex.args
        while Meta.isexpr(sig, (:where, :(::)))
            sig = sig.args[1]
        end
        Meta.isexpr(sig, :call) || return nothing
        f = sig.args[1]
        f isa Symbol || return nothing   # skip interpolated names, callable objects, ...
        Meta.isexpr(body, :block) && body.args[1] isa LineNumberNode || return nothing
        return f => body.args[1].line
    end
    function collect_definitions!(defs, ex)
        ex isa Expr || return
        if Meta.isexpr(ex, :macrocall)
            foreach(arg -> collect_definitions!(defs, arg), ex.args[3:end])
        elseif Meta.isexpr(ex, (:block, :if, :elseif))
            foreach(arg -> collect_definitions!(defs, arg), ex.args)
        else
            def = definition(ex)
            def === nothing || push!(defs, def)
        end
    end
    function find_device_functions!(defs, ex, mod::Module)
        ex isa Expr || return
        if Meta.isexpr(ex, :macrocall) && length(ex.args) >= 3 &&
           ex.args[1] in (Symbol("@device_function"), Symbol("@device_functions"))
            block_defs = Set{Pair{Symbol,Int}}()
            collect_definitions!(block_defs, ex.args[3])
            for (name, line) in block_defs
                push!(defs, (mod, name, line))
            end
        elseif Meta.isexpr(ex, :module)
            # descend into submodules (e.g. `CUDACore.CG`)
            submod = getfield(mod, ex.args[2]::Symbol)::Module
            find_device_functions!(defs, ex.args[3], submod)
        else
            foreach(arg -> find_device_functions!(defs, arg, mod), ex.args)
        end
    end

    # the CPU stub generated by `@device_function` unconditionally throws
    function is_stub(m::Method)
        ci = Base.uncompressed_ast(m)
        return any(ci.code) do stmt
            Meta.isexpr(stmt, :call) &&
                any(arg -> arg isa String && occursin("not intended for use on the CPU", arg),
                    stmt.args)
        end
    end

    ndefs = 0
    for (dir, _, files) in walkdir(root), file in files
        endswith(file, ".jl") || continue
        path = joinpath(dir, file)
        defs = Set{Tuple{Module,Symbol,Int}}()
        find_device_functions!(defs, Meta.parseall(read(path, String); filename=path), CUDACore)
        for (mod, name, line) in defs
            ndefs += 1
            if !isdefined(mod, name)
                @error "Device function $name ($file:$line) is not defined in $mod"
                @test isdefined(mod, name)
                continue
            end
            f = getfield(mod, name)

            # the stub is emitted by the macro, so it's never located at the definition:
            # any global method at that location is a definition that escaped the rewrite.
            escaped = filter(m -> String(m.file) == path && m.line == line, methods(f))
            if !isempty(escaped)
                @error "Device function $name ($file:$line) escaped @device_function: $(escaped)"
            end
            @test isempty(escaped)

            # there should be a CPU stub instead
            if !any(is_stub, methods(f))
                @error "Device function $name ($file:$line) has no CPU stub"
            end
            @test any(is_stub, methods(f))
        end
    end
    @test ndefs > 50
end
