@testset "Errors" begin
    @test sprint(showerror, cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_SUCCESS)) == "CUSTATEVECError: the operation completed successfully (code 0, CUSTATEVEC_STATUS_SUCCESS)"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_NOT_INITIALIZED)) == "the library was not initialized"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_ALLOC_FAILED)) == "the resource allocation failed"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_INVALID_VALUE)) == "an invalid value was used as an argument"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_ARCH_MISMATCH)) == "an absent device architectural feature is required"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_EXECUTION_FAILED)) == "the GPU program failed to execute"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_INTERNAL_ERROR)) == "an internal operation failed"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_NOT_SUPPORTED)) == "the API is not supported by the backend."
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_INSUFFICIENT_WORKSPACE)) == "the workspace on the device is too small to execute."
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_SAMPLER_NOT_PREPROCESSED)) == "the sampler was called prior to preprocessing."
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_NO_DEVICE_ALLOCATOR)) == "the device memory pool was not set."
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_DEVICE_ALLOCATOR_ERROR)) == "operation with the device memory pool failed"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_COMMUNICATOR_ERROR)) == "a communicator operation failed"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_LOADING_LIBRARY_FAILED)) == "loading the library failed"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_INVALID_CONFIGURATION)) == "an invalid configuration was used"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_ALREADY_INITIALIZED)) == "the library was already initialized"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_INVALID_WIRE)) == "an invalid wire was specified"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_SYSTEM_ERROR)) == "a system error occurred"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_CUDA_ERROR)) == "a CUDA error occurred"
    @test cuStateVec.description(cuStateVec.CUSTATEVECError(cuStateVec.CUSTATEVEC_STATUS_NUMERICAL_ERROR)) == "a numerical error occurred"
end
