# Automatically-generated headers for cublasmg
#
# DO NOT EDIT THIS FILE DIRECTLY.


# Automatically generated using Clang.jl

const CUBLASMG_MAJOR = 0
const CUBLASMG_MINOR = 1
const CUBLASMG_PATCH = 1

const cublasMgContext = Cvoid
const cublasMgHandle_t = Ptr{cublasMgContext}
