[general]
library_name = "libcupti"
output_file_path = "../../lib/cupti/libcupti.jl"
prologue_file_path = "./libcupti_prologue.jl"

output_ignorelist = [
    # unexpanded macro (TODO: expand during rewrite?)
    "_STRUCT_SIZE$",
    # these change often
    "^CUPTI_API_VERSION$",
]


[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true


[api]
checked_rettypes = [ "CUptiResult" ]

[api.cuptiGetResultString]
needs_context = false

[api.cuptiGetVersion]
needs_context = false
