[general]
library_name = "libcustatevec"
output_file_path = "../../lib/custatevec/src/libcustatevec.jl"
prologue_file_path = "./libcustatevec_prologue.jl"

output_ignorelist = [
    # these change often
    "CUSTATEVEC_VERSION",
    "CUSTATEVEC_VER_.*",
]


[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true


[api]
checked_rettypes = [ "custatevecStatus_t" ]

[api.custatevecLoggerSetMask]
needs_context = false

[api.custatevecGetVersion]
needs_context = false

[api.custatevecLoggerForceDisable]
needs_context = false

[api.custatevecLoggerOpenFile]
needs_context = false

[api.custatevecLoggerSetFile]
needs_context = false

[api.custatevecGetErrorString]
needs_context = false

[api.custatevecLoggerSetCallback]
needs_context = false

[api.custatevecSetWorkspace.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecAbs2SumOnZBasis.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecAbs2SumArray.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecAbs2SumArrayBatched.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecCollapseOnZBasis.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecCollapseByBitString.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecCollapseByBitStringBatched.argtypes]
2 = "CuPtr{Cvoid}"
11 = "PtrOrCuPtr{Cvoid}"

[api.custatevecMeasureOnZBasis.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecBatchMeasure.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecMeasureBatched.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecBatchMeasureWithOffset.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecApplyPauliRotation.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecApplyGeneralizedPermutationMatrixGetWorkspaceSize.argtypes]
4 = "PtrOrCuPtr{custatevecIndex_t}"
5 = "CuPtr{Cvoid}"

[api.custatevecApplyGeneralizedPermutationMatrix.argtypes]
2 = "CuPtr{Cvoid}"
5 = "PtrOrCuPtr{custatevecIndex_t}"
6 = "PtrOrCuPtr{Cvoid}"
14 = "PtrOrCuPtr{Cvoid}"

[api.custatevecComputeExpectationGetWorkspaceSize.argtypes]
4 = "PtrOrCuPtr{Cvoid}"

[api.custatevecComputeExpectationsOnPauliBasis.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecComputeExpectation.argtypes]
2 = "CuPtr{Cvoid}"
8 = "PtrOrCuPtr{Cvoid}"
14 = "CuPtr{Cvoid}"

[api.custatevecSamplerCreate.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecApplyMatrixGetWorkspaceSize.argtypes]
4 = "PtrOrCuPtr{Cvoid}"

[api.custatevecApplyMatrixBatched.argtypes]
2 = "CuPtr{Cvoid}"
9 = "PtrOrCuPtr{Cvoid}"
20 = "CuPtr{Cvoid}"

[api.custatevecApplyMatrixBatchedGetWorkspaceSize.argtypes]
8 = "PtrOrCuPtr{Cvoid}"

[api.custatevecApplyMatrix.argtypes]
2 = "CuPtr{Cvoid}"
5 = "PtrOrCuPtr{Cvoid}"
15 = "CuPtr{Cvoid}"

[api.custatevecTestMatrixTypeGetWorkspaceSize.argtypes]
3 = "PtrOrCuPtr{Cvoid}"

[api.custatevecTestMatrixType.argtypes]
4 = "PtrOrCuPtr{Cvoid}"
10 = "PtrOrCuPtr{Cvoid}"

[api.custatevecSamplerPreprocess.argtypes]
3 = "CuPtr{Cvoid}"

[api.custatevecAccessorCreate.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecAccessorCreateView.argtypes]
2 = "CuPtr{Cvoid}"

[api.custatevecSwapIndexBits.argtypes]
2 = "CuPtr{Cvoid}"
