[general]
library_name = "libcutensor"
output_file_path = "../../lib/cutensor/src/libcutensor.jl"
prologue_file_path = "./libcutensor_prologue.jl"
epilogue_file_path = "./libcutensor_epilogue.jl"

output_ignorelist = [
    # these change often
    "CUTENSOR_VERSION",
    "CUTENSOR_MAJOR",
    "CUTENSOR_MINOR",
    "CUTENSOR_PATCH",
]


[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true


[api]
checked_rettypes = [ "cutensorStatus_t" ]

[api.cutensorGetErrorString]
needs_context = false

[api.cutensorGetVersion]
needs_context = false

[api.cutensorGetCudartVersion]
needs_context = false

[api.cutensorElementwiseTrinaryExecute.argtypes]
4 = "CuPtr{Cvoid}"
6 = "CuPtr{Cvoid}"
8 = "CuPtr{Cvoid}"
9 = "CuPtr{Cvoid}"

[api.cutensorElementwiseBinaryExecute.argtypes]
4 = "CuPtr{Cvoid}"
6 = "CuPtr{Cvoid}"
7 = "CuPtr{Cvoid}"

[api.cutensorPermute.argtypes]
4 = "CuPtr{Cvoid}"
5 = "CuPtr{Cvoid}"

[api.cutensorContract.argtypes]
4 = "CuPtr{Cvoid}"
5 = "CuPtr{Cvoid}"
7 = "CuPtr{Cvoid}"
8 = "CuPtr{Cvoid}"
9 = "CuPtr{Cvoid}"

[api.cutensorReduce.argtypes]
4 = "CuPtr{Cvoid}"
6 = "CuPtr{Cvoid}"
7 = "CuPtr{Cvoid}"
8 = "CuPtr{Cvoid}"
