[general]
library_name = "libnvml()"
output_file_path = "../../lib/nvml/libnvml.jl"
prologue_file_path = "./libnvml_prologue.jl"

output_ignorelist = []


[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true


[api]
checked_rettypes = [ "nvmlReturn_t" ]

[api.nvmlInit]
needs_context = false

[api.nvmlInitWithFlags]
needs_context = false

[api.nvmlShutdown]
needs_context = false

[api.nvmlErrorString]
needs_context = false
